FROM golang:1.12-alpine

# Install git
RUN set -ex; \
    apk add --update --no-cache ca-certificates git

# Set working directory
WORKDIR /dosmj/
COPY . ./
RUN GO111MODULE=on go mod download

# Run tests
CMD CGO_ENABLED=0 go test ./...